""" libuipc """

module(
    name = "libuipc",
    version = "0.9.0",
)


bazel_dep(name = "rules_cc", version = "0.2.9")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "eigen", version = "3.4.1")
bazel_dep(name = "nlohmann_json", version = "3.12.0.bcr.1")
bazel_dep(name = "cppitertools", version = "2.2")
bazel_dep(name = "magic_enum", version = "0.9.7")
bazel_dep(name = "tinygltf", version = "2.9.6")
bazel_dep(name = "dylib", version = "2.2.1")
bazel_dep(name = "spdlog", version = "1.16.0.bcr.1")
bazel_dep(name = "cpptrace", version = "1.0.4.bcr.1")

# rules_cuda is required for CUDA toolchain support
bazel_dep(name = "rules_cuda", version = "0.2.4")
git_override(
    module_name = "rules_cuda",
    remote = "https://github.com/bazel-contrib/rules_cuda.git",
    commit = "1bf21ef1eee98042c0b2c5f39365ac39a4217c53",
)

cuda = use_extension("@rules_cuda//cuda:extensions.bzl", "toolchain")
cuda.toolkit(
    name = "cuda",
    toolkit_path = "",
)
use_repo(cuda, "cuda")
