load("@rules_cc//cc:defs.bzl", "cc_library", "cc_shared_library")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cc_library(
    name = "uipc",
    visibility = ["//visibility:public"],
    deps = [
        "//src/constitution:uipc_constitution",
        "//src/core:uipc_core",
        "//src/geometry:uipc_geometry",
        "//src/io:uipc_io",
        "//src/sanity_check:uipc_sanity_check",
    ],
)

uipc_backend_commons_srcs = glob(["backends/common/**/*.cpp"])

uipc_backend_commons_hdrs = glob([
    "backends/common/**/*.h",
    "backends/common/**/*.inl",
])

cc_library(
    name = "uipc_backends_none",
    srcs = glob(["backends/none/**/*.cpp"]) + uipc_backend_commons_srcs,
    hdrs = glob(["backends/none/**/*.h"]) + uipc_backend_commons_hdrs,
    copts = [
        "-std=c++20",
    ],
    defines = [
        "UIPC_BACKEND_EXPORT_DLL",
        "UIPC_BACKEND_DIR=R\\\"(/home/ps/Projects/libuipc/src/backends)\\\"",
        "UIPC_BACKEND_NAME=R\\\"(none)\\\"",
    ],
    includes = [
        ".",
        "backends/none",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:uipc_include",
        "@cppitertools",
        "@cpptrace",
        "@eigen",
        "@nlohmann_json//:json",
        "@spdlog",
    ],
)

uipc_backend_cuda_cu_srcs = glob(["backends/cuda/**/*.cu"])

uipc_backend_cuda_cpp_srcs = glob(["backends/cuda/**/*.cpp"]) + uipc_backend_commons_srcs

cuda_library(
    name = "uipc_backends_cuda_cu",
    srcs = uipc_backend_cuda_cu_srcs,
    hdrs = glob([
        "backends/cuda/**/*.h",
        "backends/cuda/**/*.hpp",
        "backends/cuda/**/*.inl",
    ]) + uipc_backend_commons_hdrs,
    copts = [
        "-std=c++20",
    ],
    defines = [
        "UIPC_BACKEND_EXPORT_DLL",
        "UIPC_BACKEND_DIR=R\\\"(/home/ps/Projects/libuipc/src/backends)\\\"",
        "UIPC_BACKEND_NAME=R\\\"(cuda)\\\"",
    ],
    includes = [
        ".",
        "backends/cuda",
    ],
    rdc = True,
    visibility = ["//src:__subpackages__"],
    deps = [
        "//:uipc_include",
        "@cppitertools",
        "@cpptrace",
        "@cuda//:cub",
        "@cuda//:cublas",
        "@cuda//:cusolver",
        "@cuda//:cusparse",
        "@eigen",
        "@hugooole_muda//:muda",
        "@nlohmann_json//:json",
        "@spdlog",
    ],
)

# 然后编译 C++ 文件并链接 CUDA 库
cc_library(
    name = "uipc_backends_cuda",
    srcs = uipc_backend_cuda_cpp_srcs,
    hdrs = glob([
        "backends/cuda/**/*.h",
        "backends/cuda/**/*.hpp",
        "backends/cuda/**/*.inl",
    ]) + uipc_backend_commons_hdrs,
    copts = [
        "-std=c++20",
    ],
    defines = [
        "UIPC_BACKEND_EXPORT_DLL",
        "UIPC_BACKEND_DIR=R\\\"(/home/ps/Projects/libuipc/src/backends)\\\"",
        "UIPC_BACKEND_NAME=R\\\"(cuda)\\\"",
    ],
    includes = [
        ".",
        "backends/cuda",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":uipc_backends_cuda_cu",  # 链接 CUDA 库
        "//:uipc_include",
        "//src/geometry:uipc_geometry",
        "@cppitertools",
        "@cpptrace",
        "@eigen",
        "@nlohmann_json//:json",
        "@spdlog",
    ],
)

cc_shared_library(
    name = "uipc_backends_cuda_shared",
    shared_lib_name = "libuipc_backend_cuda.so",
    visibility = ["//visibility:public"],
    dynamic_deps = [
        "//src/geometry:uipc_geometry_shared",
        "//src/core:uipc_core_shared",
    ],
    deps = [
        ":uipc_backends_cuda",
    ],
)
