load("@rules_cc//cc:defs.bzl", "cc_library", "cc_shared_library")

cc_library(
    name = "uipc_constitution",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(
        [
            "**/*.h",
            "**/*.inl",
            "**/*.hpp",
        ],
        allow_empty = True,
    ),
    includes = ["."],
    local_defines = [
        "UIPC_CONSTITUTION_EXPORT_DLL=1",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//:uipc_include",
        "//src/core:uipc_core",
        "//src/geometry:uipc_geometry",
    ],
)

cc_shared_library(
    name = "uipc_constitution_shared",
    visibility = ["//visibility:public"],
    deps = [
        ":uipc_constitution",
    ],
)
